"""add_service_duration_unit

Revision ID: 917ea7887b53
Revises: ddb4bab84448
Create Date: 2026-06-26 23:45:40.612225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917ea7887b53'
down_revision: Union[str, None] = 'ddb4bab84448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration_unit', sa.String(length=20), server_default='minutes', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration_unit')
    # ### end Alembic commands ###
