import hashlib
import random
import math
from typing import List
from app.ai_providers.base import BaseLLMProvider, BaseEmbeddingProvider

class MockLLMProvider(BaseLLMProvider):
    def generate_response(self, prompt: str, system_prompt: str = None) -> str:
        snippet = prompt[:60] + "..." if len(prompt) > 60 else prompt
        response = (
            f"[MOCK AI RESPONSE]\n"
            f"Prompt received: '{snippet}'\n"
        )
        if system_prompt:
            response += f"System Instructions: '{system_prompt}'\n"
        response += (
            "This is a simulated response generated by the EasyBiz AI fallback mock provider. "
            "Configure local Ollama or add cloud API keys in your .env to run real models."
        )
        return response


class MockEmbeddingProvider(BaseEmbeddingProvider):
    def _generate_vector(self, text: str) -> List[float]:
        import re
        import hashlib
        import random
        
        dim = 1536
        vector = [0.0] * dim
        
        # Tokenize alphanumeric words of length >= 2
        raw_words = re.findall(r'[a-zA-Z0-9]{2,}', text.lower())
        
        # Common English stop words to filter out
        stopwords = {
            "the", "and", "for", "you", "that", "this", "with", "have", "are", "was",
            "were", "but", "not", "she", "her", "his", "they", "them", "their", "our",
            "what", "where", "when", "how", "who", "which", "about", "your", "will", "can",
            "does", "did", "do", "in", "on", "at", "to", "of", "a", "an", "is"
        }
        
        # Simple plural suffix stripping
        words = []
        for w in raw_words:
            if w in stopwords:
                continue
            if w.endswith('s') and len(w) > 3 and not w.endswith('ss'):
                w = w[:-1]
            words.append(w)
        
        has_val = False
        for word in words:
            # Hash word to a deterministic index [0, 1535]
            h = int(hashlib.md5(word.encode("utf-8")).hexdigest(), 16)
            idx = h % dim
            vector[idx] += 1.0
            has_val = True
            
        # If no keywords found, fallback to hash-based pseudo-random vector
        if not has_val:
            h_fallback = int(hashlib.md5(text.encode("utf-8")).hexdigest(), 16)
            rng = random.Random(h_fallback)
            vector = [rng.uniform(-0.1, 0.1) for _ in range(dim)]
            
        # Normalize the vector (L2 norm)
        square_sum = sum(x * x for x in vector)
        norm = math.sqrt(square_sum)
        if norm > 0:
            vector = [x / norm for x in vector]
            
        return vector

    def embed_text(self, text: str) -> List[float]:
        return self._generate_vector(text)

    def embed_batch(self, texts: List[str]) -> List[List[float]]:
        return [self._generate_vector(text) for text in texts]
